name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }}
        PUBLISH_REPOSITORY: daniloqueiroz/me
        BRANCH: gh-pages
        PUBLISH_DIR: ./public
